development:
  adapter: sqlite3
  database: db/ajaxful_rating_jquery_demo_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/ajaxful_rating_jquery_demo_test.sqlite3
  pool: 5
  timeout: 5000
  
production:
  adapter: sqlite3
  database: db/ajaxful_rating_jquery_demo.sqlite3
  pool: 5
  timeout: 5000
